name: network-wait
version: 0.1.0.0
github: "mbg/network-wait"
license: MIT
author: "Michael B. Gale"
maintainer: "github@michael-gale.co.uk"
copyright: "2022 Michael B. Gale"

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: A lightweight Haskell library for waiting on networked services to become available.
category: Network

description: Please see the README on GitHub at <https://github.com/mbg/network-wait#readme>

dependencies:
  - base >= 4.7 && < 5
  - exceptions
  - network
  - retry

library:
  source-dirs: src

tests:
  network-wait-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - network-wait
      - tasty
      - tasty-hunit
